FROM node:18-alpine

WORKDIR /FRONT

COPY package.json /frontend/
COPY package-lock.json /frontend/ 
RUN npm install

COPY src/ /frontend/src
COPY public/ /forntend/public

EXPOSE 3000

CMD ["npm", "start"]

