FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /FRONT

# Copy the package.json and package-lock.json (if available) to the working directory
COPY package.json /frontend/
COPY package-lock.json /frontend/ 
# Install dependencies
RUN npm install

# Copy the source and public directories to the working directory
COPY src/ /frontend/src
COPY public/ /forntend/public

# Expose the port on which your application will run
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]

