# Version de Docker Compose
version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000" 
    volumes:
      - ./backend/app:/code/app
      - ./backend/chat.csv:/code/chat.csv  
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_APP_NAME=RH Chatbot
    depends_on:
      - backend
    restart: unless-stopped